django_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("photos/", include("photos.urls", namespace="photo")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_dev/core/urls.py
from django.urls import path
from .views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
]

django_dev/photos/urls.py
from django.urls import path
from. import views

app_name = "photos"

urlpatterns = [
    path("", views.AlbumLV.as_view(), name="index"),
    path("album/", views.AlbumLV.as_view(), name="album_list"),
    path("album/<int:pk>/", views.AlbumDV.as_view(), name="album_detail"),
    path("photo/<int:pk>/", views.PhotoDV.as_view(), name="photo_detail")
]

django_dev/photos/models.py
from django.db import models
from django.urls import reverse
from .fields import ThumbnailImageField

class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField("One line description", max_length=100, blank=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("photo:album_detail", args=("self.id",))

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField("TITLE", max_length=30)
    description = models.TextField("Photo Description", blank=True)
    image = ThumbnailImageField(upload_to="photo/%Y/%m")
    upload_dt = models.DateTimeField("Upload Date", auto_now_add=True)

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("photo:photo_detail", args=(self.id,))

django_dev/photos/views.py
from django.views.generic import ListView, DetailView
from .models import Photo, Album
from users.mixins import LoggedInOnlyView


class AlbumLV(LoggedInOnlyView, ListView):
    model = Album


class AlbumDV(LoggedInOnlyView,DetailView):
    model = Album


class PhotoDV(LoggedInOnlyView,DetailView):
    model = Photo

django_dev/templates/photos/album_detail.html
{% extends 'base2.html' %}

{% load static%}

{% block title %}
    Gallery
{% endblock %}


{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_a.css' %}">
{% endblock %}

{% block content %}

<section id="photo" class="section">
    <div class="container">
        &emsp;
        <h1>{{ object.name }}</h1>
        <hr style="margin: 0px 0px 30px; background-color: var(--color-background-red);">
        <div class="row">
            {% for photo in object.photo_set.all %}
            <div class="col-md-3 mb-5">
                <h2>{{ photo.title }}</h2>
                <div class="thumbnail">
                    <a href="{{ photo.get_absolute_url }}">
                        <img src=" {{ photo.image.thumb_url }}" style="width: 100%;">
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>     
    </div>
</section>
{% endblock %}

django_dev/templates/photos/album_list.html
{% extends 'base2.html' %}

{% load static %}

{% block title %}
    Gallery
{% endblock %}
    

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_a.css' %}">
{% endblock %}

{% block content %}
    
<section id="photo" class="section__photo">
    <div class="container__photo">

    {% for item in object_list %}
        <div class="mt-5"> 
            <a class="h2" style="text-decoration: none" href="{% url 'photos:album_detail' item.id %}">
                <h1 style="display: flex">{{ item.name }}</h1>
            </a>
        </div>

        <hr style="margin: 0px 0px 30px; background-color: var(--color-background-red);">

        <div class="row">
            {% for photo in item.photo_set.all %}
            <div class="ml-5">
                <div class="thumbnail" style="margin: 0 40px 50px;">
                    <a href="{{ photo.get_absolute_url }}">
                        <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                    </a>
                </div>
            </div>            
            {% endfor %}
        </div>
        {% endfor %}

        <h1 style="display: flex">T-SNE Video</h1>
        <hr style="margin: 0px 0px 30px; background-color: var(--color-background-red);">
        <section class="album__video">
            <video controls src="{% static 'video/t-sne.mp4' %}" width="90%" ></video>
        </section>

        &emsp;

        <h1 style="display: flex">GAN GIF</h1>
        <hr style="margin: 0px 0px 30px; background-color: var(--color-background-red);">
        <section class="gan" 
        style="
        display: flex;
        flex-wrap: wrap;
        ">
            
            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">비빔밥</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/Bibimbap.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">치킨</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/Chicken.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">갈비탕</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/galbitang.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">파전</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/Pajeon.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">피자</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/pizza.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">소세지볶음</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/sausage.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">육개장</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/Yukgaejang.gif' %}" style="width:280px">
                </div>
            </div>

            <div class="gan__food" style="margin: 0 30px 30px;">
                <h2 class="gan__title">김밥</h2>
                <div class="gan__gif">
                    <img src="{% static 'gif/Kimbab.gif' %}" style="width:280px">
                </div>
            </div>
            


        </section>

    </div>
</section>
{% endblock %}

django_dev/templates/photos/photo_detail.html
{% extends 'base2.html' %}

{% load static %}

{% block title %}
    Gallery
{% endblock %}
    
{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_a.css' %}">
{% endblock %}

{% block content %}


<section id="photo" class="section">
    <div class="container">
        &emsp;
        <h1>Detailed description</h1>
        <h2>{{ object.title }}</h2>
        <div class="object__image">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 80%;">
            </a>
        </div>
        &emsp;
        <div class="object__description">
            {% if object.description %}
            <p>{{ object.description|linebreaks }}<p>
            {% else %}
            <p>(blank)</p>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}