django_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("photos/", include("photos.urls", namespace="photo")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_dev/core/urls.py
from django.urls import path
from .views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
]

django_dev/foods/urls.py
from django.urls import path
from .views import predictImage, ClassifierView, FoodPlaceSearch, HistoryView

app_name = "foods"

urlpatterns = [
    path("photos/create/", ClassifierView.as_view(), name="classifier"),
    path("photos/create/predictImage/", predictImage, name="predictImage"),
    path("place/search/", FoodPlaceSearch, name="FoodPlaceSearch"),
    path("history/<int:pk>/", HistoryView.as_view(), name="history"),
    
]

django_dev/foods/models.py
from django.db import models
from core.models import TimeStampedModel

class Food(TimeStampedModel):

    """ Food Model Definition """

    name = models.CharField(max_length=20)
    image = models.ImageField(upload_to="foods/%Y/%m/%d", blank=True)
    user = models.ForeignKey("users.User", related_name="foods", on_delete=models.CASCADE, null=True)
    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.name

django_dev/foods/views.py
import json
import re
import os
from PIL import Image
import numpy as np
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from tensorflow.keras.models import load_model
from .models import Food
from users.models import User
from users.mixins import LoggedInOnlyView

with open("./data/label_info.json", "r", encoding="utf-8-sig") as f:
    label_info = json.load(f)

with open("./data/aifoodie_hashtags.json", "r", encoding="utf-8-sig") as f:
    hashtags = json.load(f)


class ClassifierView(LoggedInOnlyView ,TemplateView):
    template_name = "foods/classifier.html"


def predictImage(request):
    fileObj = request.FILES["filePath"]

    # 한글 파일명 영어로 바꿔주기
    if re.findall("[ㄱ-ㅎ가-힣]", fileObj.name) != []:
        tail = os.path.splitext(fileObj.name)[1]
        nums = np.random.randint(0, 9999999)
        fileObj.name = "image_file_" + str(nums) + tail

    users = User.objects.get(pk=request.user.pk)
    # DB
    food = Food(name="", image=fileObj, user=users)
    food.save()

    search = Food.objects.filter(user=users)[0].image
    model = load_model("./models/new_model.h5")

    testimage = search.file
    food_image = Image.open(testimage)
    food_image = food_image.convert("RGB")
    food_image = food_image.resize((360, 360))
    food_image = np.array(food_image)
    x = food_image[np.newaxis, :, :, :]
    pred = model.predict(x)
    index = np.argmax(pred[0])
    predictedLabel = label_info[str(index)]

    try:
        if hashtags[str(index)]:
            # 몇 개의 해시태그를 뽑을까?
            num = np.random.randint(3, len(hashtags[str(index)]))
            hashtag = np.random.choice(hashtags[str(index)], num, replace=False)
            print(hashtag)
    except IndexError:
        pass

    food.name = predictedLabel
    food.save()
    context = {
        "filePathName": search.url,
        "predictedLabel": predictedLabel,
        "hashtags": hashtag,
    }

    return render(request, "foods/classifier_r.html", context)


def FoodPlaceSearch(request):
    search = Food.objects.order_by("-pk")[0].name
    context = {"search": search}
    return render(request, "foods/search_place.html", context)

class HistoryView(LoggedInOnlyView,ListView):
    model = Food
    template_name = "foods/history.html"

    def get_queryset(self):
        return Food.objects.filter(user=self.request.user).order_by("-created")

django_dev/templates/foods/classifier.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
    Classifier
{% endblock %}
    

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_c.css' %}">
<script src="{% static 'javascripts/main_c.js' %}" defer></script>
{% endblock %}


{% block content %}
    
<!-- Classifier -->
<section id="classifier" class="section">
    <div class="container">
      <h1>
        </br>Let's Classify Food Image!
      </h1>        
      <h2>음식 이미지만 업로드 해주세요🍔🍕🍟🌭🍿</h2>

      <form method="post" action="{% url 'foods:predictImage' %}" name="ImageUpload" enctype="multipart/form-data" >
        {% csrf_token %}
        <div class="avatar-upload">
              <div class="avatar-edit">
                  <input type="file" id="imageUpload" accept=".png, .jpg, .jpeg" name="filePath" />
                  <label for="imageUpload"></label>
              </div>
              <div class="avatar-preview" onclick="imageUpload.click();">
                <img class="file-upload-image" id="profile-image" src="#" alt="your image" style="display: none;"/>
                  <div id="imagePreview" style="background-image: url({% static 'imgs/bono.jpg' %});"></div>
              </div>
          </div>

          <button type="button" class="btn_upload" onclick="imageUpload.click();">
            🔍 Upload
          </button>
          <br>
          <input type="submit" class="btn_upload" value="Submit">
      </form>
    </div>
  </section>


{% endblock %}
    

django_dev/templates/foods/classifier_r.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
    Classifier
{% endblock %}

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_c.css' %}">
<link rel="stylesheet" href="{% static 'css/style_h.css' %}">

<script src="{% static 'javascripts/main_c.js' %}" defer></script>
{% endblock %}

{% block content %}

<section id="classifier" class="section">
    <div class="container">
      <h1>
        </br>Let's Classify Food Image!
      </h1>        
      <h2>{{predictedLabel}} 올리셨군요!!😁</h2>

      <div class="image__box">
          <img src="{{filePathName}}" width="100%" heigh="100%">
      </div>

      <div class="hashtag">
        {% for h in hashtags %}
          <h3 class="hashtag__color">#{{h}} </h3>
        {% endfor %}
      </div>

      <a href="{% url 'foods:FoodPlaceSearch' %}"><button class="btn_upload">
        🔎주변 맛집 보기
      </button></a>

      <a href="{% url 'foods:classifier' %}"><button class="btn_upload">
        👋되돌아가기
      </button></a>
    </div>
  </section>


{% endblock %}

django_dev/templates/foods/history.html
{% extends 'base2.html' %}

{% load static %}

{% block title %}
    History
{% endblock %}
    

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_hi.css' %}">
{% endblock %}

{% block content %}

<section id="history" class="section__history">
    &emsp;
    <h1>업로드한 음식 사진 히스토리📜</h1>
    &emsp;
    <div class="container__history">
        {% for history in object_list %}
        <div class="history__box">
            <img src="{{history.image.url}}" class="history__image" style="width: 500px;">
            <div>
                <h2>{{ history.name }}</h2>
                <h3>{{ history.created }}</h3>
            </div>
        </div>
        {% endfor%}           
    </div>
</section>

{% endblock %}

django_dev/templates/foods/search_place.html
{% extends 'base2.html' %}
{% load static %}

{% block title %}
    Search
{% endblock %}
    

{% block extra-style %}
<link rel="stylesheet" href="{% static 'css/style_c.css' %}">
<script src="{% static 'javascripts/main_c.js' %}" defer></script>
{% endblock %}


{% block content %}

<!-- Food Search Map -->

<section id="classifier" class="section">
    <div class="container">
        <h1>
        </br>Let's Search Food Place!
        </h1>        
        <h2>주변 음식점🍚</h2>

        <div class="place">
            <div id="map" style="width:80%; height:700px; margin:50px auto 100px; z-index: 0"></div>
        </div>
        
        <a href="{% url 'foods:classifier' %}"><button class="btn_upload">
            👋되돌아가기
        </button></a>

    </div>
</section>

<!-- Food Search Map -->
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d9b233b6fb70f3927bd1aa1ee26fdcb7&libraries=services,clusterer,drawing"></script>


<script>
    // 마커를 클릭하면 장소명을 표출할 인포윈도우 입니다
    var infowindow = new kakao.maps.InfoWindow({zIndex:1});
    
    var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = {
            center: new kakao.maps.LatLng(37.566826, 126.9786567), // 지도의 중심좌표
            level: 1 // 지도의 확대 레벨
        };  
    
    // 지도를 생성합니다    
    var map = new kakao.maps.Map(mapContainer, mapOption); 
    
    // 장소 검색 객체를 생성합니다
    var ps = new kakao.maps.services.Places(); 
    
    // 키워드로 장소를 검색합니다
    ps.keywordSearch("{{search}}", placesSearchCB); 
    
    // 키워드 검색 완료 시 호출되는 콜백함수 입니다
    function placesSearchCB (data, status, pagination) {
        if (status === kakao.maps.services.Status.OK) {
    
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정하기위해
            // LatLngBounds 객체에 좌표를 추가합니다
            var bounds = new kakao.maps.LatLngBounds();
    
            for (var i=0; i<data.length; i++) {
                displayMarker(data[i]);    
                bounds.extend(new kakao.maps.LatLng(data[i].y, data[i].x));
            }       
    
            // 검색된 장소 위치를 기준으로 지도 범위를 재설정합니다
            map.setBounds(bounds);
        } 
    }
    
    // 지도에 마커를 표시하는 함수입니다
    function displayMarker(place) {
        
        // 마커를 생성하고 지도에 표시합니다
        var marker = new kakao.maps.Marker({
            map: map,
            position: new kakao.maps.LatLng(place.y, place.x) 
        });
    
        // 마커에 클릭이벤트를 등록합니다
        kakao.maps.event.addListener(marker, 'click', function() {
            // 마커를 클릭하면 장소명이 인포윈도우에 표출됩니다
            infowindow.setContent('<div style="padding:5px;font-size:12px;">' + place.place_name + '</div>');
            infowindow.open(map, marker);
        });
    }
</script>

{% endblock %}