django_dev/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("foods/", include("foods.urls", namespace="foods")),
    path("photos/", include("photos.urls", namespace="photo")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_dev/core/urls.py
from django.urls import path
from .views import HomeView

app_name = "core"

urlpatterns = [
    path("", HomeView.as_view(), name="index"),
]

django_dev/foods/urls.py
from django.urls import path
from .views import predictImage, ClassifierView, FoodPlaceSearch, HistoryView

app_name = "foods"

urlpatterns = [
    path("photos/create/", ClassifierView.as_view(), name="classifier"),
    path("photos/create/predictImage/", predictImage, name="predictImage"),
    path("place/search/", FoodPlaceSearch, name="FoodPlaceSearch"),
    path("history/<int:pk>/", HistoryView.as_view(), name="history"),
    
]

django_dev/users/urls.py
from django.urls import path
from .views import LoginView, RegisterView, log_out

app_name = "users"


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("register/", RegisterView.as_view(), name="register"),
    path("logout/", log_out, name="logout"),
]

django_dev/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <meta property="og:title" content="AIFFEL Final Hackathon">
  <meta property="og:description" content="Hackathon 2nd and 3rd will conduct food classification under the team name AI FOODIE. We will find and tune the classification model suitable for the food to find the highest recognition rate. In addition, we plan to create a classification model that best suits food.">
  <script src="https://kit.fontawesome.com/8cc10ba7fd.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="icon" href="{% static 'imgs/ice.ico' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/style_b.css' %}">

  {% block extra-style%}{% endblock %}
  <script src="{% static 'javascripts/main.js' %}" defer></script>
  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d9b233b6fb70f3927bd1aa1ee26fdcb7&libraries=services,clusterer,drawing"></script>
  <!-- <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d9b233b6fb70f3927bd1aa1ee26fdcb7"></script> -->
</head>

<body>
  <!-- Navbar -->
  {% if user.is_authenticated %}
    <nav id="navbar">
      <div class="navbar__logo">
        <a href="{% url 'core:index' %}"><i class="fas fa-ice-cream"> </i> AIFOODIE</a>
      </div>
        <ul class="navbar__menu">
          <li class="navbar__menu__item "><a href="{% url 'foods:classifier'%}">Classifier</a></li>
          <li class="navbar__menu__item "><a href="{% url 'foods:history' pk=user.pk %}">History</a></li>
          <li class="navbar__menu__item active" data-link="#home">Home</li>
          <li class="navbar__menu__item" data-link="#about">About</li>
          <li class="navbar__menu__item" data-link="#skills">Result</li>
          <li class="navbar__menu__item" data-link="#presentation">Presentation</li>
          <li class="navbar__menu__item" data-link="#messages">Message</li>
          <li class="navbar__menu__item" data-link="#modulabmap">Map</li>
          <li class="navbar__menu__item" data-link="#contact">Contact</li>
          <li class="navbar__menu__item"><a href="{% url 'users:logout' %}">Logout</a></li>
        </ul>
  {% else %}
    <nav id="navbar">
      <div class="navbar__logo">
        <a href="{% url 'core:index' %}"><i class="fas fa-ice-cream"> </i> AIFOODIE</a>
      </div>
        <ul class="navbar__menu">
          <li class="navbar__menu__item "><a href="{% url 'foods:classifier'%}">Classifier</a></li>
          <li class="navbar__menu__item active" data-link="#home">Home</li>
          <li class="navbar__menu__item" data-link="#about">About</li>
          <li class="navbar__menu__item" data-link="#skills">Result</li>
          <li class="navbar__menu__item" data-link="#presentation">Presentation</li>
          <li class="navbar__menu__item" data-link="#messages">Message</li>
          <li class="navbar__menu__item" data-link="#modulabmap">Map</li>
          <li class="navbar__menu__item" data-link="#contact">Contact</li>
          <li class="navbar__menu__item"><a href="{% url 'users:login' %}">Login</a></li>
          <li class="navbar__menu__item"><a href="{% url 'users:register' %}">SignUp</a></li>
        </ul>
    {% endif %}

    <!-- Toggle button-->
    <button class="navbar__toggle-btn">
      <i class="fas fa-bars"></i>
    </button>

  </nav>

{% block content %}

{% endblock %}

  <!-- Contact-->
  <section id="contact" class="section">
    <h1 class="contact__title">Contact</h1>
    <h2 class="contact__email"><a href="https://github.com/Development-On-Saturday" target="_blank">https://github.com/Development-On-Saturday</a></h2>
      <a href="https://github.com/Development-On-Saturday" target="_blank" class="contact__link">
        <i class="fa fa-github"></i>
      </a>
    </div>
    <p class="contact__rights">
      Copyright ⓒ 2020 AIFFEL_FOODIE. All rights reserved.
    </p>
  </section>

</body>

django_dev/templates/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="Tay's beta version Website Portfolio">
  <meta name="author" content="Tay">
  <script src="https://kit.fontawesome.com/8cc10ba7fd.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="icon" href="{% static 'imgs/ice.ico' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block extra-style%}{% endblock %}
  <script src="{% static 'javascripts/main.js' %}" defer></script>
</head>

  <!-- Navbar -->
  <nav id="navbar">
    <div class="navbar__logo">
      <a href="{% url 'core:index' %}"><i class="fas fa-ice-cream"> </i> AIFOODIE</a>
    </div>
      <ul class="navbar__menu">
        <li class="navbar__menu__item "><a href="{% url 'core:index'%}">Home</a></li>
        <li class="navbar__menu__item "><a href="{% url 'foods:classifier'%}">Classifier</a></li>
        <li class="navbar__menu__item "><a href="{% url 'foods:history' pk=user.pk %}">History</a></li>
        <li class="navbar__menu__item"><a href="{% url 'users:logout' %}">Logout</a></li>
      </ul>

    <!-- Toggle button-->
    <button class="navbar__toggle-btn">
      <i class="fas fa-bars"></i>
    </button>

  </nav>



{% block content %}

{% endblock %}


  <!-- Contact-->
  <section id="contact" class="section">
    <h1 class="contact__title">Contact</h1>
    <h2 class="contact__email"><a href="https://github.com/Development-On-Saturday" target="_blank">https://github.com/Development-On-Saturday</a></h2>
      <a href="https://github.com/Development-On-Saturday" target="_blank" class="contact__link">
        <i class="fa fa-github"></i>
      </a>
    </div>
    <p class="contact__rights">
      Copyright ⓒ 2020 AIFFEL_FOODIE. All rights reserved.
    </p>
  </section>
</body>